### ISSUE TITLE
Build fail with cordova-android 11 / AGP 7

### ISSUE THREAD

**Issue by ath0mas** [okhiroyuki/cordova-plugin-barcodescanner#5]
### Expected Behaviour
`cordova build` should be successful with [cordova-android 11](https://cordova.apache.org/announcements/2022/07/12/cordova-android-release-11.0.0.html) like with previous versions.

Confirmed to be OK with cordova-android 10.1.2.

### Actual Behaviour
```
1: Task failed with an exception.
-----------
* Where:
Script 'C:\cdv-scanner\hello\platforms\android\@red-mobile\cordova-plugin-barcodescanner\hello-barcodescanner.gradle' line: 9

* What went wrong:
A problem occurred evaluating script.
> Could not find method compile() for arguments [{name=barcodescanner-release-2.1.7, ext=aar}] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

#### Steps to Reproduce
```
cordova create hello com.example.hello HelloWorld
cd hello/
cordova platform add android@11.0.0
cordova plugin add @red-mobile/cordova-plugin-barcodescanner
cordova build
```

#### Cordova CLI version and cordova platform version

    cordova: 11.0.0
    cordova-android: 11.0.0

#### Plugin version

    cordova plugin version | grep @red-mobile/cordova-plugin-barcodescanner: 9.0.7

#### Logs taken while reproducing problem
While building with cordova-android 10.1.2, the following warning is shown:
```
WARNING:: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed in version 7.0 of the Android Gradle plugin.
For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
```
And yes, cordova-android 11 updated `AGP 4.2.2 -> 7.1.0 -> 7.2.1` (see https://github.com/apache/cordova-android/pull/1410 and https://github.com/apache/cordova-android/pull/1446)!

**Comment by eh2001** [comment]
To those facing Android v11 with build error, edit the file "platforms/android/@red-mobile/cordova-plugin-barcodescanner/app-barcodescanner.gradle", replace the "compile" to "implementation", then build again.

compile(name:'barcodescanner-release-2.1.7', ext:'aar')

to

implementation(name:'barcodescanner-release-2.1.7', ext:'aar')

**Comment by ath0mas** [comment]
@eh2001 see my PR #6 on this

until review and merge, I published my own fork [ns0m/cordova-plugin-ns0m-barcodescanner](https://github.com/ns0m/cordova-plugin-ns0m-barcodescanner/releases) to npm [cordova-plugin-ns0m-barcodescanner](https://www.npmjs.com/package/cordova-plugin-ns0m-barcodescanner)
and my [v9.1.0](https://github.com/ns0m/cordova-plugin-ns0m-barcodescanner/releases/tag/v9.1.0) for the issue here
